version: "3"
services:
  app:
    container_name: benign-filter-container
    build:
      context: ./
      dockerfile: dockerfile
    working_dir: /app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 8080:80
      
networks:
  default:
    external:
      name: benign-filter-network
