version: "2"
services:
  app:
    container_name: benign-filter-container
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:80
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata01:
    driver: local

networks:
  default:
    external:
      name: benign-filter-network
